[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, s-maxage=31536000, immutable"

  for = "/livecodes/*"
  [headers.values]
    cache-control = "public, max-age=31536000, s-maxage=31536000, immutable"

