name: CI-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check typos on code
        uses: crate-ci/typos@master
        with:
          config: ./typos.toml

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # - name: Cache Node modules
      #   id: cache-npm
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ matrix.node-version }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          BUILD_INCLUDE_LOCALES: ${{ startsWith(github.head_ref, 'i18n/') }}

      - name: Test
        run: npm run test
        env:
          CI: true
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
